# docker build --build-arg VERSION=<version> --build-arg SOURCE_DATE_EPOCH=<epoch> --output=. -f Dockerfile.binary .

# golang:1.23.6
FROM golang@sha256:927112936d6b496ed95f55f362cc09da6e3e624ef868814c56d55bd7323e0959 AS build

WORKDIR /go/src/app
COPY src/ .
COPY reproducible_build.sh .

ARG VERSION=v0.0.0
ARG SOURCE_DATE_EPOCH=0

RUN bash reproducible_build.sh

FROM scratch AS export

COPY --from=build /go/src/app/fileway /
