FROM golang:latest AS build

WORKDIR /go/src/app
COPY src/ .

RUN CGO_ENABLED=0  go build -trimpath -a -o fileway -tags="netgo osusergo" -ldflags='-w -extldflags "-static"'

# Now copy it into a caddy image.
FROM caddy:latest

COPY --from=build /go/src/app/fileway /

ENV FILEWAY_SECRET_HASHES=""
ENV BASE_ADDRESS=""

EXPOSE 80 443

CMD ["/bin/sh", "-c", "/fileway & caddy reverse-proxy --from $BASE_ADDRESS --to http://localhost:8080"]
