# docker build --build-arg VERSION=<version> --build-arg SOURCE_DATE_EPOCH=<epoch> --output=. -f Dockerfile.binary .

# golang:1.24.1
FROM golang@sha256:c5adecdb7b3f8c5ca3c88648a861882849cc8b02fed68ece31e25de88ad13418 AS build

WORKDIR /go/src/app
COPY src/ .
COPY reproducible_build.sh .

ARG VERSION=v0.0.0
ARG SOURCE_DATE_EPOCH=0

RUN bash reproducible_build.sh

FROM scratch AS export

COPY --from=build /go/src/app/fileway /
