# Builds the binary in the current dir
# docker build --build-arg VERSION=<version> --build-arg SOURCE_DATE_EPOCH=<epoch> --output=. -f Dockerfile.binary .

# golang:1.26.6-trixie pinned for reproducible builds
FROM golang@sha256:ab563819a16cfe5faff0f96a8bb598fbb0e400ab2ac751996e60abcb23b106a3 AS build

WORKDIR /go/src/app
COPY src/ .
COPY reproducible_build.sh .

ARG VERSION=v0.0.0
ARG SOURCE_DATE_EPOCH=0

RUN bash reproducible_build.sh

FROM scratch AS export

COPY --from=build /go/src/app/fileway /
